[pytest]
minversion = 6.0
addopts = 
    --cov=api_base
    --cov-report=term-missing
    --capture=tee-sys
testpaths = 
    tests

# Display output for debugging (especially in CI)
log_cli = true
log_cli_level = INFO