activity_list = [
    "Airport Tour",
    "Alpine skiing",
    "Archery",
    "Arts",
    "Assist the disabled",
    "Auto mechanics & repair",
    "Aviation",
    "Backpacking",
    "Barbecue party",
    "Beach party",
    "Block party",
    "Bowling",
    "Camping trip",
    "Canoeing",
    "Car wash",
    "Career clinic",
    "Chemistry",
    "Child care",
    "Christmas party",
    "Cinematography",
    "Civil defense",
    "College panel discussion",
    "Communications",
    "Community cleanup proj.",
    "Conservation proj.",
    "Cooking",
    "COPE",
    "Cross-country skiing",
    "Cycling",
    "Dance",
    "Dating panel",
    "Diet & nutrition",
    "Emergency prep.",
    "Energy",
    "Ethics debate",
    "Fashion show",
    "Financial investing",
    "Fire safety",
    "First aid/CPR/EMT",
    "Fishing",
    "Food drive",
    "Genealogy",
    "Go-carts",
    "Gourmet cooking",
    "Halloween party",
    "Ham radio",
    "Home repairs",
    "Horseback riding",
    "How to buy a car",
    "Hunting",
    "Ice-skating",
    "Job interview skills",
    "Leadership skills",
    "Leave no Trace",
    "Lifesaving",
    "Long boat cruise",
    "Military obstacle course",
    "Mountaineering",
    "Olympics",
    "Orienteering",
    "Part-time job clinic",
    "Photography",
    "Physical fitness",
    "Picnic",
    "Pistol shooting",
    "Planetarium",
    "Plants & wildlife",
    "Produce a play",
    "Public speaking",
    "Rappelling",
    "Rifle shooting",
    "River rafting",
    "Road rally",
    "Rock climbing",
    "Rocketry",
    "Sailing/cruise",
    "Scholarships",
    "Scuba",
    "Service projects",
    "Shotgun shooting",
    "Snorkeling",
    "Spelunking",
    "Sports day/Olympics",
    "Sports medicine",
    "Swim meet",
    "Swimming party",
    "Tennis clinic",
    "Train trip",
    "University visit",
    "Visit a court",
    "Visit ballet",
    "Visit opera",
    "Visit symphony",
    "Water skiing",
    "Watercraft",
    "Wilderness survival",
    "Winter sports"
]
